### ISSUE TITLE
publish snap package?

### ISSUE THREAD

**Issue by anonymouse64** [tartley/cbeams#2]
Hi, this app is really cool, but not being a regular python dev, I would prefer to have this command available as a snap package which is more "visible" and more easily installable for me on my various devices that may not have pip available (i.e. ubuntu core devices).

Would you consider creating a snap package for this?

**Comment by tartley** [comment]
Yeah, I would. Good idea.

**Comment by tartley** [comment]
PR welcome, obviously... :-)

**Comment by anonymouse64** [comment]
Well I tried for about 5 minutes before hitting pythonic things that unfortunately above my head, but I think the issue is that your setup.py doesn't support `bdist`? It seems to only support `sdist`:

```
$ snapcraft --debug
Launching a container.
Waiting for container to be ready
Waiting for network to be ready...
snapd is not logged in, snap install commands will use sudo
snap "core20" has no updates available
Copying needed target link from the system /usr/bin/python3.8
Updating pull step for cbeams (source changed)
Updating build step for cbeams ('pull' step changed)
+ python3 -m venv /root/parts/cbeams/install
+ [ -f setup.py ]
+ pip install -U .
Processing /root/parts/cbeams/build
Collecting blessings>=1.6
  Using cached blessings-1.7-py3-none-any.whl (18 kB)
Collecting docopt>=0.6.1
  Using cached docopt-0.6.2.tar.gz (25 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: cbeams, docopt
  Building wheel for cbeams (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/parts/cbeams/install/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-bh7y7xbl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-bh7y7xbl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iux14mqn
       cwd: /tmp/pip-req-build-bh7y7xbl/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for cbeams
  Running setup.py clean for cbeams
  Building wheel for docopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/parts/cbeams/install/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iawpbzze/docopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iawpbzze/docopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-no09iwqt
       cwd: /tmp/pip-install-iawpbzze/docopt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for docopt
  Running setup.py clean for docopt
Failed to build cbeams docopt
Installing collected packages: six, blessings, docopt, cbeams
    Running setup.py install for docopt ... done
    Running setup.py install for cbeams ... done
Successfully installed blessings-1.7 cbeams-1.0.3 docopt-0.6.2 six-1.15.0
+ find /root/parts/cbeams/install -type f -executable
+ head -1 /root/parts/cbeams/install/bin/easy_install
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/easy_install
+ head -1 /root/parts/cbeams/install/bin/pip
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/pip
+ head -1 /root/parts/cbeams/install/bin/pip3
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/pip3
+ head -1 /root/parts/cbeams/install/bin/pip3.8
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/pip3.8
+ head -1 /root/parts/cbeams/install/bin/easy_install-3.8
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/easy_install-3.8
+ head -1 /root/parts/cbeams/install/bin/cbeams
+ grep -q python
+ sed -r 1 s|#\!.*python3?$|#\!/usr/bin/env python3| -i /root/parts/cbeams/install/bin/cbeams
+ interp_path=/root/parts/cbeams/install/bin/python3
+ [ -f /root/parts/cbeams/install/bin/python3 ]
+ readlink /root/parts/cbeams/install/bin/python3
+ current_link=/root/stage/bin/python3
+ echo+  /root/stage/bin/python3
grep -q /root/parts/cbeams/install
Cleaning later steps and re-staging cbeams ('build' step changed)
Priming cbeams 
Snapping |                                                                                                                                                                       
Snapped cbeams_v1.0.3_amd64.snap
```

note that I consider a snapcraft bug that it still produced a .snap file when it clearly failed at doing something with setuptools...

Here is the output when I try to run that built snap:

```
$ snap run cbeams
Traceback (most recent call last):
  File "/snap/cbeams/x1/bin/cbeams", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cbeams==1.0.3' distribution was not found and is required by the application
```

and here's the snapcraft.yaml I tried:

```yaml
name: cbeams
base: core20
adopt-info: cbeams
summary: A CLI program which draws pretty animated colored circles in the terminal.

description: |
  A command-line program which draws pretty animated colored circles in the terminal.
  > I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched c-beams glitter in the dark, near the Tannhäuser Gate. All those moments will be lost, in time, like tears in rain. Time to die.

grade: stable
confinement: strict

apps:
  cbeams:
    command: bin/cbeams

parts:
  cbeams:
    plugin: python
    source: .
    requirements:
      - requirements.txt
    build-packages:
      # for setting the version of the snap
      - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --always --tags --dirty)
```
